# Generated by Django 3.2.4 on 2021-06-22 05:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='img/story/preview')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('order_num', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='story_app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='StoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreDetailedUrl', models.SlugField()),
                ('moreDetailedText', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=50)),
                ('content_url', models.SlugField()),
                ('duration', models.TimeField(default=datetime.time(0, 0, 15))),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='story_app.story')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('subs_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField()),
                ('story_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='story_app.storyfile')),
                ('subs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='story_app.subscribers')),
            ],
        ),
    ]
