# Generated by Django 3.2.4 on 2021-06-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyfile',
            old_name='story',
            new_name='story_id',
        ),
    ]
